### ISSUE TITLE
vga refactoring

### ISSUE THREAD

**Issue by teverett** [kurtmweber/CosmOS#11]
I'm confused by the vga stuff.  it appears in both /video and /console.  Can some of it be refactored into /dev/display?

**Comment by kurtmweber** [comment]
So what I did was split the stuff that directly deals with the VGA hardware proper in /video, while the part that implements the console abstractions for a VGA console is in /console.  The part in /console calls the /video routines to manipulate the hardware as needed, but it doesn't (or shouldn't) do any of that directly.

**Comment by teverett** [comment]
awesome.  at some point, after the current giant PR (sorry about that), we can move /video into /dev.

**Comment by teverett** [comment]
Completed
